const d3 = require("d3");

const test = [
            {
                "time": 1499490000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 69.87,
                "apparentTemperature": 69.93,
                "dewPoint": 60.33,
                "humidity": 0.72,
                "windSpeed": 7.01,
                "windGust": 8.62,
                "windBearing": 345,
                "visibility": 10,
                "cloudCover": 0.06,
                "pressure": 1013.25,
                "ozone": 333.98,
                "uvIndex": 0
            },
            {
                "time": 1499493600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 69.05,
                "apparentTemperature": 69.05,
                "dewPoint": 59.19,
                "humidity": 0.71,
                "windSpeed": 5.79,
                "windGust": 6.12,
                "windBearing": 322,
                "visibility": 10,
                "cloudCover": 0.03,
                "pressure": 1013.27,
                "ozone": 330.55,
                "uvIndex": 0
            },
            {
                "time": 1499497200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.85,
                "apparentTemperature": 67.85,
                "dewPoint": 59.19,
                "humidity": 0.74,
                "windSpeed": 6.61,
                "windGust": 7.62,
                "windBearing": 324,
                "visibility": 10,
                "cloudCover": 0,
                "pressure": 1013.53,
                "ozone": 330.12,
                "uvIndex": 0
            },
            {
                "time": 1499500800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.74,
                "apparentTemperature": 66.75,
                "dewPoint": 59.41,
                "humidity": 0.77,
                "windSpeed": 8.85,
                "windGust": 11.22,
                "windBearing": 342,
                "visibility": 9.86,
                "cloudCover": 0.01,
                "pressure": 1013.88,
                "ozone": 330.65,
                "uvIndex": 0
            },
            {
                "time": 1499504400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.16,
                "apparentTemperature": 66.16,
                "dewPoint": 59.21,
                "humidity": 0.78,
                "windSpeed": 9.26,
                "windGust": 13.2,
                "windBearing": 350,
                "visibility": 9.89,
                "cloudCover": 0.01,
                "pressure": 1014.37,
                "ozone": 332.53,
                "uvIndex": 0
            },
            {
                "time": 1499508000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.72,
                "apparentTemperature": 65.72,
                "dewPoint": 59.15,
                "humidity": 0.79,
                "windSpeed": 9.53,
                "windGust": 12.91,
                "windBearing": 357,
                "visibility": 10,
                "cloudCover": 0.05,
                "pressure": 1014.65,
                "ozone": 336.46,
                "uvIndex": 0
            },
            {
                "time": 1499511600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.11,
                "apparentTemperature": 66.11,
                "dewPoint": 58.87,
                "humidity": 0.78,
                "windSpeed": 10.13,
                "windGust": 14.11,
                "windBearing": 4,
                "visibility": 10,
                "cloudCover": 0.09,
                "pressure": 1014.96,
                "ozone": 341.69,
                "uvIndex": 0
            },
            {
                "time": 1499515200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.49,
                "apparentTemperature": 67.49,
                "dewPoint": 58.28,
                "humidity": 0.72,
                "windSpeed": 9.8,
                "windGust": 12.73,
                "windBearing": 8,
                "visibility": 10,
                "cloudCover": 0,
                "pressure": 1015.5,
                "ozone": 346.92,
                "uvIndex": 1
            },
            {
                "time": 1499518800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.12,
                "apparentTemperature": 68.12,
                "dewPoint": 57.83,
                "humidity": 0.7,
                "windSpeed": 9.91,
                "windGust": 11.85,
                "windBearing": 9,
                "visibility": 10,
                "cloudCover": 0.05,
                "pressure": 1016.04,
                "ozone": 349.23,
                "uvIndex": 1
            },
            {
                "time": 1499522400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 69.12,
                "apparentTemperature": 69.12,
                "dewPoint": 57.08,
                "humidity": 0.66,
                "windSpeed": 9.18,
                "windGust": 11.42,
                "windBearing": 5,
                "visibility": 10,
                "cloudCover": 0.07,
                "pressure": 1016.59,
                "ozone": 350.3,
                "uvIndex": 2
            },
            {
                "time": 1499526000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 70.61,
                "apparentTemperature": 70.61,
                "dewPoint": 55.78,
                "humidity": 0.59,
                "windSpeed": 8.29,
                "windGust": 10.97,
                "windBearing": 358,
                "visibility": 10,
                "cloudCover": 0.1,
                "pressure": 1017.07,
                "ozone": 350.16,
                "uvIndex": 4
            },
            {
                "time": 1499529600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 71.57,
                "apparentTemperature": 71.57,
                "dewPoint": 55.6,
                "humidity": 0.57,
                "windSpeed": 7.71,
                "windGust": 10.48,
                "windBearing": 356,
                "visibility": 10,
                "cloudCover": 0.25,
                "pressure": 1017.22,
                "ozone": 348.37,
                "uvIndex": 6
            },
            {
                "time": 1499533200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 72.66,
                "apparentTemperature": 72.66,
                "dewPoint": 55.62,
                "humidity": 0.55,
                "windSpeed": 7.6,
                "windGust": 10.03,
                "windBearing": 0,
                "visibility": 10,
                "cloudCover": 0.26,
                "pressure": 1017.21,
                "ozone": 345.34,
                "uvIndex": 7
            },
            {
                "time": 1499536800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 73.67,
                "apparentTemperature": 73.67,
                "dewPoint": 56.32,
                "humidity": 0.55,
                "windSpeed": 7.2,
                "windGust": 10.8,
                "windBearing": 0,
                "visibility": 10,
                "cloudCover": 0.14,
                "pressure": 1017.12,
                "ozone": 342.64,
                "uvIndex": 9
            },
            {
                "time": 1499540400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 74.86,
                "apparentTemperature": 74.86,
                "dewPoint": 56.28,
                "humidity": 0.52,
                "windSpeed": 7.36,
                "windGust": 10.72,
                "windBearing": 14,
                "visibility": 10,
                "cloudCover": 0.11,
                "pressure": 1016.75,
                "ozone": 340.68,
                "uvIndex": 8
            },
            {
                "time": 1499544000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 75.89,
                "apparentTemperature": 75.89,
                "dewPoint": 56.01,
                "humidity": 0.5,
                "windSpeed": 7.16,
                "windGust": 10.47,
                "windBearing": 28,
                "visibility": 10,
                "cloudCover": 0.06,
                "pressure": 1016.51,
                "ozone": 338.98,
                "uvIndex": 6
            },
            {
                "time": 1499547600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 76.54,
                "apparentTemperature": 76.54,
                "dewPoint": 55.72,
                "humidity": 0.49,
                "windSpeed": 6.69,
                "windGust": 9.69,
                "windBearing": 41,
                "visibility": 10,
                "cloudCover": 0.04,
                "pressure": 1016.3,
                "ozone": 337.67,
                "uvIndex": 4
            },
            {
                "time": 1499551200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 76.6,
                "apparentTemperature": 76.6,
                "dewPoint": 55.54,
                "humidity": 0.48,
                "windSpeed": 6.03,
                "windGust": 8.62,
                "windBearing": 54,
                "visibility": 10,
                "cloudCover": 0.04,
                "pressure": 1015.96,
                "ozone": 336.99,
                "uvIndex": 2
            },
            {
                "time": 1499554800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 76.32,
                "apparentTemperature": 76.32,
                "dewPoint": 55.26,
                "humidity": 0.48,
                "windSpeed": 5.26,
                "windGust": 7.21,
                "windBearing": 69,
                "visibility": 10,
                "cloudCover": 0.03,
                "pressure": 1015.91,
                "ozone": 336.66,
                "uvIndex": 1
            },
            {
                "time": 1499558400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 75.64,
                "apparentTemperature": 75.64,
                "dewPoint": 55.1,
                "humidity": 0.49,
                "windSpeed": 4.44,
                "windGust": 5.69,
                "windBearing": 88,
                "visibility": 10,
                "cloudCover": 0.02,
                "pressure": 1015.98,
                "ozone": 336.11,
                "uvIndex": 0
            },
            {
                "time": 1499562000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 74.66,
                "apparentTemperature": 74.66,
                "dewPoint": 54.93,
                "humidity": 0.5,
                "windSpeed": 4.27,
                "windGust": 5.63,
                "windBearing": 109,
                "visibility": 10,
                "cloudCover": 0.02,
                "pressure": 1016.22,
                "ozone": 335.1,
                "uvIndex": 0
            },
            {
                "time": 1499565600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 73.27,
                "apparentTemperature": 73.27,
                "dewPoint": 55.09,
                "humidity": 0.53,
                "windSpeed": 4.28,
                "windGust": 5.68,
                "windBearing": 133,
                "visibility": 10,
                "cloudCover": 0.02,
                "pressure": 1016.72,
                "ozone": 333.93,
                "uvIndex": 0
            },
            {
                "time": 1499569200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0019,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 72.17,
                "apparentTemperature": 72.17,
                "dewPoint": 55.29,
                "humidity": 0.55,
                "windSpeed": 4.79,
                "windGust": 6.8,
                "windBearing": 159,
                "visibility": 10,
                "cloudCover": 0.01,
                "pressure": 1017.16,
                "ozone": 332.89,
                "uvIndex": 0
            },
            {
                "time": 1499572800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 71.4,
                "apparentTemperature": 71.4,
                "dewPoint": 55.45,
                "humidity": 0.57,
                "windSpeed": 5.74,
                "windGust": 8.12,
                "windBearing": 174,
                "visibility": 10,
                "cloudCover": 0.01,
                "pressure": 1017.16,
                "ozone": 331.91,
                "uvIndex": 0
            }
]



function getData(choice) {
	return test.map((obj) => {
		return {time: (new Date(obj.time * 1000)), count: obj[choice]}
	}); 
}

var choices = ["humidity"];

var data = getData(choices[0]);
console.log(data);

var margin = {top: 20, right: 20, bottom: 20, left: 20},
w = 1080 - (margin.left + margin.right),
h = 480 - (margin.top + margin.bottom);
		
var transform='translate(' + margin.left + ',' + margin.top + ')';
		
var x = d3.scaleTime().domain(d3.extent(data, (d) => d.time)).rangeRound([0, w]);
var y = d3.scaleLinear().domain(d3.extent(data, (d) => d.count)).rangeRound([h, 0]);	
				
var line = d3.line().x(function(d) { return x(d.time);}).y(function(d) { return y(d.count); });
        	           		
var xAxis = d3.axisBottom(x);
var yAxis = d3.axisLeft(y);
 
var yGrid = d3.axisLeft(y)
  	.scale(y)
  	.ticks(5)
  	.tickSize(-w, 0, 0)
   	.tickFormat("");

console.log(line(data));

